In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from DQN_Acrobot import *

In [4]:
env = gym.make('Acrobot-v1')

[2018-12-05 09:44:03,589] Making new env: Acrobot-v1


In [45]:
agent = DQNAgent(env)

In [6]:
agent.run_experiment(no_frame=10)

In [7]:
mini_batch = random.sample(agent.memory, 4)

In [8]:
mini_batch

[(array([ 0.99971993, -0.02366567, -0.1843911 ,  0.98285295, -0.58488889,
          1.98685641]),
  2,
  -1.0,
  False,
  array([ 0.99030392, -0.13891776, -0.49620482,  0.86820549, -0.56372818,
          1.35262284])),
 (array([ 0.89143243, -0.45315364,  0.75884716, -0.65126875,  0.38443077,
          0.78803055]),
  2,
  -1.0,
  False,
  array([ 0.93375242, -0.35791957,  0.87696999, -0.48054515,  0.63017292,
          1.30702429])),
 (array([ 0.9997901 , -0.02048813,  0.26274699, -0.96486477, -0.35838054,
          1.62772492]),
  1,
  -1.0,
  False,
  array([ 0.99478597, -0.10198472,  0.62701935, -0.77900368, -0.4610393 ,
          2.47976064])),
 (array([ 0.77325329,  0.63409727,  0.67352457,  0.73916483, -1.19807669,
          1.51936766]),
  0,
  -1.0,
  False,
  array([ 0.9228288 ,  0.38521033,  0.45958366,  0.88813448, -1.66296548,
          1.00594298]))]

In [15]:
mini_batch[0][3]

False

In [11]:
last_observations = np.array([rep[0] for rep in mini_batch])

In [12]:
current_observations = np.array([rep[-1] for rep in mini_batch])

In [9]:
agent.load_model('save_model/-1000.0.h5')

In [15]:
last_observations

array([[ 0.99971993, -0.02366567, -0.1843911 ,  0.98285295, -0.58488889,
         1.98685641],
       [ 0.89143243, -0.45315364,  0.75884716, -0.65126875,  0.38443077,
         0.78803055],
       [ 0.9997901 , -0.02048813,  0.26274699, -0.96486477, -0.35838054,
         1.62772492],
       [ 0.77325329,  0.63409727,  0.67352457,  0.73916483, -1.19807669,
         1.51936766]])

In [16]:
current_observations

array([[ 0.99030392, -0.13891776, -0.49620482,  0.86820549, -0.56372818,
         1.35262284],
       [ 0.93375242, -0.35791957,  0.87696999, -0.48054515,  0.63017292,
         1.30702429],
       [ 0.99478597, -0.10198472,  0.62701935, -0.77900368, -0.4610393 ,
         2.47976064],
       [ 0.9228288 ,  0.38521033,  0.45958366,  0.88813448, -1.66296548,
         1.00594298]])

In [36]:
target = agent.model.predict(last_observations)
target

array([[-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001]], dtype=float32)

In [20]:
next_q_for_action_selection = agent.model.predict(current_observations)
next_q_for_action_selection

array([[-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001]], dtype=float32)

In [22]:
next_q = agent.target_model.predict(current_observations)
next_q

array([[-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001]], dtype=float32)

In [23]:
next_action_sel = np.argmax(next_q_for_action_selection[0])
next_action_sel

1

In [26]:
current_action = mini_batch[0][1]
current_action

2

In [28]:
reward = mini_batch[0][2]
reward

-1.0

In [29]:
done = mini_batch[0][3]
done

False

In [37]:
target[0][current_action] = reward + (1 - done) * agent.gamma * next_q[0][next_action_sel]

In [42]:
next_q[0][1]

-1.0

In [43]:
last_observations

array([[ 0.99971993, -0.02366567, -0.1843911 ,  0.98285295, -0.58488889,
         1.98685641],
       [ 0.89143243, -0.45315364,  0.75884716, -0.65126875,  0.38443077,
         0.78803055],
       [ 0.9997901 , -0.02048813,  0.26274699, -0.96486477, -0.35838054,
         1.62772492],
       [ 0.77325329,  0.63409727,  0.67352457,  0.73916483, -1.19807669,
         1.51936766]])

In [44]:
target

array([[-1.0000001, -1.       , -1.99     ],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001],
       [-1.0000001, -1.       , -1.0000001]], dtype=float32)

In [24]:
target = agent.model.predict(last_observations)

array([[-3.539497  , -2.688147  , -0.40856874],
       [-2.9589062 , -2.0333192 ,  0.5177854 ],
       [-0.5854352 , -0.21609813, -0.85621285],
       [-2.514013  , -0.49889636, -1.1855227 ]], dtype=float32)

In [25]:
next_q   = agent.target_model.predict(current_observations)

In [28]:
next_q_for_action_selection = agent.model.predict(current_observations)

In [29]:
next_q_for_action_selection

array([[-3.4271479 , -2.8100157 , -1.0829484 ],
       [-4.4287004 , -3.1751976 , -0.63300097],
       [-1.6735563 , -0.02429992, -0.87160885],
       [-2.6315053 , -0.7889645 , -0.38181722]], dtype=float32)

In [32]:
np.argmax(next_q_for_action_selection[0])

2

In [ ]:
act_sel = self.model.pred_network.predict(new_observations)

In [35]:
False *1

0

In [46]:
agent.run_experiment()

Model Evaluation Result at 50793
Avg Reward in 10 Episodes: -1000.0
Avg Time Step Each Episode: 1000.0
-------------------------------------------
Model Evaluation Result at 100271
Avg Reward in 10 Episodes: -1000.0
Avg Time Step Each Episode: 1000.0
-------------------------------------------
Model Evaluation Result at 150080
Avg Reward in 10 Episodes: -1000.0
Avg Time Step Each Episode: 1000.0
-------------------------------------------
Model Evaluation Result at 200864
Avg Reward in 10 Episodes: -1000.0
Avg Time Step Each Episode: 1000.0
-------------------------------------------
Model Evaluation Result at 250335
Avg Reward in 10 Episodes: -1000.0
Avg Time Step Each Episode: 1000.0
-------------------------------------------
Model Evaluation Result at 300788
Avg Reward in 10 Episodes: -1000.0
Avg Time Step Each Episode: 1000.0
-------------------------------------------
Model Evaluation Result at 350088
Avg Reward in 10 Episodes: -1000.0
Avg Time Step Each Episode: 1000.0
---------

KeyboardInterrupt: 

In [47]:
agent = DQNAgent(env)

In [48]:
agent.load_model('save_model/-454.h5')

In [ ]:
agent.run_experiment()

Model Evaluation Result at 50085
Avg Reward in 10 Episodes: -263.6
Avg Time Step Each Episode: 264.6
-------------------------------------------
